[project]
name = "pollox-max"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.5.0",
    "jsonlines>=4.0.0",
    "openai>=1.70.0",
    "pip>=25.0.1",
    "transformers>=4.50.3",
]
